fix(typescript): fix folding, symbols for TS plugin for .ts
volarjs/volar.js pull request #227
Opened 2024-07-22 03:57 UTC by johnsoncodehk

cc @ShenQingchuan

2024-07-23 08:10 UTC, ShenQingchuan commented
Is there any practical way that I can use this modified code in Vue Vine source code and check whether it does work?

2024-10-22 00:28 UTC, Milad335t requested changes
Mil

2024-10-23 14:38 UTC, ShenQingchuan commented
@johnsoncodehk 

This feature in Vue Vine extension seems to be resolved in the last few versions of Volar, so I think we may close this  draft? or is there anything else left?

Another problem is linked with Vue Vine `vineProp` jump to definition, but it'd be better for me to open a new PR.

2025-06-17 16:39 UTC, johnsoncodehk commented
Closed due to lost context. (I no longer know how to debug this problem.)

2025-06-17 16:39 UTC, closed without merging